Adding ACME to CM Menu  - Create acme.mdx
smallstep/docs-old pull request #116
Opened 2021-08-31 19:24 UTC by mikemaxey

Still in draft. don't pull yet.

2021-08-31 22:17 UTC, mikemaxey commented
This PR Adds:
 - new ACME page under /docs/certificate-manager
 - new ACME RA page under /docs/registration-authority
updates:
 - /docs/certificate-manager/ = new content
 - /docs/registration-authority/acme-for-cas = updated metadata description
 - contents.yml = added new RA and CM menus

2021-08-31 23:47 UTC, tashian commented
I've added the RA mode graphic to `master` on the web repo

2021-09-01 00:00 UTC, tashian requested changes
added a few comments

2021-09-01 00:00 UTC, tashian commented on contents.yaml
> +    path: certificate_manager/acme
this should be `certificate-manager/acme`

2021-09-01 00:00 UTC, tashian commented on registration-authorities/acme-for-certificate-manager.mdx
> +    Follow the instructions in our [Registration Authority documentation](https://smallstep.com/docs/step-ca/configuration#registration-authority-ra-mode), using the following `/etc/step-ca/config/ca
Let's use a relative URL here so it works in staging environments

2021-09-01 00:00 UTC, tashian commented on registration-authorities/acme-for-certificate-manager.mdx
> +    We've written a [tutorial for configuring popular ACME clients to use internal ACME](https://smallstep.com/docs/tutorials/acme-protocol-acme-clients).
Let's use a relative URL here so it works in staging environments

2021-09-01 00:00 UTC, tashian commented on certificate-manager/acme.mdx
> +3. Configure your ACME client(s) and issue certificates. [Find Yours >](https://smallstep.com/docs/tutorials/acme-protocol-acme-clients)
Let's use a relative URL here so it works in staging environments

2021-09-01 00:00 UTC, tashian commented on certificate-manager/acme.mdx
> +![ACME Registration Authority](/uploads/cm-hiw-ra.svg "In this example, the Smallstep ACME RA runs within the local network or VPC and responds to ACME requests from internal infrastructure and workl
I'm not sure what this image is supposed to be, but it's not appearing for me in preview

2021-09-02 18:53 UTC, mikemaxey commented on contents.yaml
> +    path: certificate_manager/acme
fixed. thx!

2021-09-02 20:01 UTC, mikemaxey commented on registration-authorities/acme-for-certificate-manager.mdx
> +    Follow the instructions in our [Registration Authority documentation](https://smallstep.com/docs/step-ca/configuration#registration-authority-ra-mode), using the following `/etc/step-ca/config/ca
I used a complete URL so the page will open in a new tab/window. The idea is when they are done they go back to the original tab and start the next step.

2021-09-02 20:01 UTC, mikemaxey commented on registration-authorities/acme-for-certificate-manager.mdx
> +    We've written a [tutorial for configuring popular ACME clients to use internal ACME](https://smallstep.com/docs/tutorials/acme-protocol-acme-clients).
Same comment. Want pop up.

2021-09-02 20:01 UTC, mikemaxey commented on certificate-manager/acme.mdx
> +3. Configure your ACME client(s) and issue certificates. [Find Yours >](https://smallstep.com/docs/tutorials/acme-protocol-acme-clients)
Same comment. Want pop up.

2021-09-02 20:06 UTC, mikemaxey commented on certificate-manager/acme.mdx
> +![ACME Registration Authority](/uploads/cm-hiw-ra.svg "In this example, the Smallstep ACME RA runs within the local network or VPC and responds to ACME requests from internal infrastructure and workl
uploaded ia-cloud-ra-challenge-client.svg to static/graphics and updated page.

2021-09-02 20:28 UTC, devadvocado commented on registration-authorities/acme-for-certificate-manager.mdx
> +1. Distribute your root CA certificate and start issuing certs. 🥳
numbers moving forward are incorrect

2021-09-03 21:26 UTC, merged