An SSH template example that adds principals passed from an IdP
smallstep/docs-old pull request #5
Opened 2020-12-02 21:52 UTC by tashian

2020-12-03 20:07 UTC, maraino approved these changes
I've added a couple of notes, but it looks good to me.

2020-12-03 20:07 UTC, maraino commented on step-ca/configuration.mdx
> +In other words, you can use single sign-on with G Suite, Okta, Active Directory,
I'm not sure if `Active Directory` supports OIDC, but I'm sure `Azure Active Directory` does. 

When I was looking at AWS Active Directory, they only mention SAML authentication.

2020-12-03 20:07 UTC, maraino commented on step-ca/configuration.mdx
> +  and that's what this variable represents.
👍

2020-12-03 20:07 UTC, maraino commented on step-ca/configuration.mdx
> +    "principals": {{ toJson ((concat .Principals (splitList " " .Token.groups)) | uniq) }},
I trust you with this :)

2020-12-03 22:47 UTC, dopey commented on step-ca/configuration.mdx
> +  The EailAddresses SANs provided in the certificate request
email

2020-12-03 22:53 UTC, dopey commented on step-ca/configuration.mdx
>      If you've added an OIDC admin user to you CA configuration,
_your_ CA configuration

2020-12-03 22:56 UTC, dopey commented on step-ca/configuration.mdx
> +First, configure a custom `groups` claim with your identity provider, and add the claim to the payload of the ID token.
This is something we could probably use an example with. Would be cool if we could do drop down examples for AWS, Azure, gcp

2020-12-03 22:58 UTC, dopey requested changes
left a few comments with requested grammar changes.

2020-12-07 21:14 UTC, tashian commented on step-ca/configuration.mdx
> +    "principals": {{ toJson ((concat .Principals (splitList " " .Token.groups)) | uniq) }},
It ran! 🥇

2020-12-07 21:19 UTC, merged