Docs for StepCAS & CloudCAS
smallstep/docs-old pull request #57
Opened 2021-03-29 22:49 UTC by tashian

This PR:
* Adds an overview & explainer of RA modes
* Incorporates the docs from https://github.com/smallstep/certificates/edit/master/docs/cas.md for CloudCAS
* Adds new docs for StepCAS.

2021-03-29 23:28 UTC, tashian commented
@maraino How does this look to you? I've tried to incorporate everything from the Slack thread where we discussed StepCAS

2021-03-30 17:53 UTC, maraino requested changes

2021-03-30 17:53 UTC, maraino commented on step-ca/certificate-authority-core-concepts.mdx
> +An RA acts as a front-end to a CA, authenticating certificate requests from its clients before passing them along to an upstream Certificate Auothority that will issue the certificates.
Typo in Auothority

2021-03-30 17:53 UTC, maraino commented on step-ca/configuration.mdx
> +An RA acts as a front-end to a CA, authenticating certificate requests from its clients before passing them along to an upstream Certificate Auothority that will issue the certificates.
Same typo here.

2021-03-30 17:53 UTC, maraino commented on step-ca/configuration.mdx
> +		},
I would put here the JWK, it's easier to manage. And later add the example of the X5C.

2021-03-30 17:53 UTC, maraino commented on step-ca/configuration.mdx
> +* `step ca renew` (mTLS renewals) are not yet supported between `step` clients and an RA.
CloudCAS supports `step ca renew`, StepCAS doesn't.

2021-03-30 17:53 UTC, maraino commented on step-ca/configuration.mdx
> +* ACME load balancing between RAs is not supported.
I think it will work using `mysql` as the db backend.

2021-03-30 17:53 UTC, maraino commented on step-ca/configuration.mdx
> +	"key": "/Users/mariano/.step/secrets/provisioner.key"
The key parameter is supported, but if it's not passed it will get the encrypted one from the list of provisioners.
The recommended configuration would be 
```
{
   "type" : "jwk",
   "provisioner": "ra@smallstep.com"
}
```

2021-03-30 17:53 UTC, maraino commented on step-ca/configuration.mdx
> +	"key": "/Users/mariano/.step/secrets/provisioner.key"
And use it with the `--issuer-password-file`.

2021-03-30 17:53 UTC, maraino commented on step-ca/configuration.mdx
> +	"key": "/Users/mariano/.step/secrets/provisioner.key"
This simpler configuration is the one that should be in the main example.

2021-03-30 17:53 UTC, maraino commented on step-ca/configuration.mdx
> +      "credentialsFile": "/path/to/credentials.json",
"credentialsFile" is one of the ways cloud credentials can be passed, they can also be passed with the file pointed by environment variable `GOOGLE_APPLICATION_CREDENTIALS` or using a service account. See details in https://cloud.google.com/docs/authentication/getting-started

2021-03-30 17:53 UTC, maraino commented on step-ca/configuration.mdx
> +      "certificateAuthority": "projects/<name>/locations/<loc>/certificateAuthorities/<intermediate-name>"
Just to let you know, this will change when CloudCAS `v1` is deployed, right now we're using a beta version. And Google doesn't plan to support any kind of migration.

2021-03-30 17:53 UTC, maraino commented on step-ca/configuration.mdx
> +}
The PKI and ca.json can be created using `step ca init --ra cloudcas`

2021-03-30 18:33 UTC, tashian commented on step-ca/configuration.mdx
> +}
If they do `step ca init --ra cloudcas`, do they still need to create Google KMS key rings and keys? (I think the answer is no?)

Does this flow work?
1. Enable privateca in GCP
2. Create IAM polices and service account, and export credentials
3. Run `step ca init --ra cloudcas`

2021-03-30 18:53 UTC, tashian commented on step-ca/configuration.mdx
> +	"key": "/Users/mariano/.step/secrets/provisioner.key"
Oh! this makes total sense now 💡

2021-03-31 00:16 UTC, tashian commented on step-ca/configuration.mdx
> +}
🖕🏼 I went with this flow in my updated version BTW

2021-03-31 00:27 UTC, tashian commented
Ok @maraino I revamped this and resolved all these issues based on your feedback.
I just want to confirm that the CloudCAS setup steps are correct when using `step ca init --ra cloudcas`.
Beyond that, unless you have other feedback, I think this is ready.

2021-03-31 02:30 UTC, maraino approved these changes
LGTM, I've added a comment.

2021-03-31 02:30 UTC, maraino commented on step-ca/configuration.mdx
> +  "key": "/Users/mariano/.step/secrets/provisioner.enc.key",
You haven't explained what this key is. It's basically the same key (in PEM format) that we get from the CA. It will only make sense to set this if:
* You don't want to distribute the key from the CA. This is actually possible, if you don't define `encryptedKey`, but it will force to manually sign the token.
* You want to use a different password.

It's not yet supported, but for example if we want to sign the token with an HSM that would be another reason to have a key there.

2021-03-31 19:41 UTC, merged